### ISSUE TITLE
Add yii2-sqlite3-full-support to packagist

### ISSUE THREAD

**Issue by umbalaconmeogia** [santilin/yii2-sqlite3-full-support#1]
Should you change the namespace in QueryBuilder.php to santilin\sqlite and add it to packagist?

Not sure if it is right or not, bug I hope then it can be used by configuring db like this.
```php
'db' => [
    'class' => 'yii\db\sqlite\Connection',
    // ...
    'queryBuilder' =>santilin\sqlite\QueryBuilder,
    ],
],
```

**Comment by santilin** [comment]
You are right. I'll do it in a few days' time.

**Comment by santilin** [comment]
It's not possible to change the base class for the connection `queryBuilder` because `dbConnection::setQueryBuilder` calls `dbConnection::getQueryBuilder` that calls `Schema::getQueryBuilder` and none of these calls allow injection of a new QueryBuilder object. 
There are a pair of issues about this: https://github.com/yiisoft/yii2/issues/9740 and https://github.com/yiisoft/yii2/issues/7674

Until this is solved, you must use controllerMap in your app entry point:

Yii::$classMap['yii\db\sqlite\QueryBuilder'] = "@vendor/santilin/yii2-sqlite3-full-support/src/sqlite/QueryBuilder.php";

**Comment by santilin** [comment]
I have updated my extension so that there is no need to set up anything. It uses now the Yii2 extension loading feature to set up the classMap.

**Comment by santilin** [comment]
Added: https://packagist.org/packages/santilin/yii2-sqlite3-full-support
